branches:
  only:
  - master

language: node_js

node_js:
  - '9.4.0'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - echo "Installing packages."
  - yarn install
  - echo "Starting Webpack Build."
  - npm run build
  - echo "Firebase Deploy."
  - firebase deploy

install:
  - npm install -g yarn
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
