language: node_js

node_js:
  - '9.4.0'

cache:
  yarn: true
  directories:
    - node_modules

script:
  - echo "Starting Webpack Build."
  - webpack --config build/webpack.prod.conf.js
  - echo "Firebase Deploy."
  - firebase deploy

install:
  - npm install -g yarn
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
